title: lesh.monster
author: lesh
permalink: :title
email: seokwonmin@naver.com
description: Occasional posts on technology and stuff
baseurl: ""
url: https://lesh.monster
markdown: kramdown
highlighter: rouge
exclude:
  - "*.sketch"
  - "vendor"
data:
  menu:
    - name: Blog
      link: /blog/
    - name: Talks
      link: /talks/
    - name: Projects
      link: /projects/
    - name: About
      link: /about/
